### PR TITLE
Import json in extensions.

### PR DESCRIPTION
**Pull request by jcape**
- Add 'import json' to the local_extensions scripts.

### Motivation

When run locally from within pipx, cookiecutter errors for the lack of this, and cruft errors for the lack of local_extensions period. Let's start with cookiecutter.

### CODE REVIEW

**Comment by jcape** [comment]
Current dependencies on/for this PR:
* main
  * **PR #26** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/cookiecutters/26" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/cookiecutters/26?utm_source=stack-comment).

**Comment by jcape** [comment]
https://github.com/cruft/cruft/issues/172

**Review by nick-mobilecoin — APPROVED** [review]
Guessing the repo name extension will need to be removed as well, but that can be a follow on PR.

**Comment by jcape** [comment]
> Guessing the repo name extension will need to be removed as well, but that can be a follow on PR.

Yeah, I'm not sure of a nice way to handle that, TBH

**Pull request merged**
